offers = [{'Item': 'A', 'Price': 50, 'Special offers': '3A for 130, 5A for 200'},
 {'Item': 'B', 'Price': 30, 'Special offers': '2B for 45'},
 {'Item': 'C', 'Price': 20, 'Special offers': None},
 {'Item': 'D', 'Price': 15, 'Special offers': None},
 {'Item': 'E', 'Price': 40, 'Special offers': '2E get one B free'},
 {'Item': 'F', 'Price': 10, 'Special offers': '2F get one F free'},
 {'Item': 'G', 'Price': 20, 'Special offers': None},
 {'Item': 'H', 'Price': 10, 'Special offers': '5H for 45, 10H for 80'},
 {'Item': 'I', 'Price': 35, 'Special offers': None},
 {'Item': 'J', 'Price': 60, 'Special offers': None},
 {'Item': 'K', 'Price': 80, 'Special offers': '2K for 150'},
 {'Item': 'L', 'Price': 90, 'Special offers': None},
 {'Item': 'M', 'Price': 15, 'Special offers': None},
 {'Item': 'N', 'Price': 40, 'Special offers': '3N get one M free'},
 {'Item': 'O', 'Price': 10, 'Special offers': None},
 {'Item': 'P', 'Price': 50, 'Special offers': '5P for 200'},
 {'Item': 'Q', 'Price': 30, 'Special offers': '3Q for 80'},
 {'Item': 'R', 'Price': 50, 'Special offers': '3R get one Q free'},
 {'Item': 'S', 'Price': 30, 'Special offers': None},
 {'Item': 'T', 'Price': 20, 'Special offers': None},
 {'Item': 'U', 'Price': 40, 'Special offers': '3U get one U free'},
 {'Item': 'V', 'Price': 50, 'Special offers': '2V for 90, 3V for 130'},
 {'Item': 'W', 'Price': 20, 'Special offers': None},
 {'Item': 'X', 'Price': 90, 'Special offers': None},
 {'Item': 'Y', 'Price': 10, 'Special offers': None},
 {'Item': 'Z', 'Price': 50, 'Special offers': None}]