offers = {'A': {'Price': 50, 'Special offers': '3A for 130, 5A for 200'},
'B': {'Price': 30, 'Special offers': '2B for 45'},
'C': {'Price': 20, 'Special offers': ""},
'D': {'Price': 15, 'Special offers': ""},
'E': {'Price': 40, 'Special offers': '2E get one B free'},
'F': {'Price': 10, 'Special offers': '2F get one F free'},
'G': {'Price': 20, 'Special offers': ""},
'H': {'Price': 10, 'Special offers': '5H for 45, 10H for 80'},
'I': {'Price': 35, 'Special offers': ""},
'J': {'Price': 60, 'Special offers': ""},
'K': {'Price': 80, 'Special offers': '2K for 150'},
'L': {'Price': 90, 'Special offers': ""},
'M': {'Price': 15, 'Special offers': ""},
'N': {'Price': 40, 'Special offers': '3N get one M free'},
'O': {'Price': 10, 'Special offers': ""},
'P': {'Price': 50, 'Special offers': '5P for 200'},
'Q': {'Price': 30, 'Special offers': '3Q for 80'},
'R': {'Price': 50, 'Special offers': '3R get one Q free'},
'S': {'Price': 30, 'Special offers': ""},
'T': {'Price': 20, 'Special offers': ""},
'U': {'Price': 40, 'Special offers': '3U get one U free'},
'V': {'Price': 50, 'Special offers': '2V for 90, 3V for 130'},
'W': {'Price': 20, 'Special offers': ""},
'X': {'Price': 90, 'Special offers': ""},
'Y': {'Price': 10, 'Special offers': ""},
'Z': {'Price': 50, 'Special offers': ""},
}